# -*- coding: utf-8 -*-
"""Repeat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_o_LgF_12b6QjRiAAGjhakB7VmbSn_dF

#En çok tekrar eden sayıyı ve ne kadar tekrar ettiğini bulan program.
"""

numbers = [1, 3 , 7 , 4, 3 , 0 , 3 , 6 , 3]
a = max(numbers , key = numbers.count)
b = numbers.count(max(numbers , key = numbers.count))
print("En çok tekrar eden {} sayısıdır ve {} kere tekrar etmiştir.".format(a,b))