# -*- coding: utf-8 -*-
"""think_number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cYgD4u9l3WAgU3wioG4QUs9xbBfB2Xt

#Kullanıcının sistemde kayıtlı olan sayıyı tahmin etmesini sağlayan python kodunu giriniz
"""

answer = 25

question = "What number am I thinking about?"
print("Let's play the guessing game")


while True:
  guess = int(input(question))
  
  if guess < answer:
      print('Little higher')
  elif guess > answer: 
      print('Little lower')
  else:
      print('Are you a mindreader')
      break